apache/kyuubi

.gitignore, src/main/scala/org/apache/spark/KyuubiConf.scala, src/main/scala/org/apache/spark/KyuubiSparkUtil.scala, src/main/scala/yaooqinn/kyuubi/server/KyuubiServer.scala, src/main/scala/yaooqinn/kyuubi/utils/ReflectUtils.scala, src/test/scala/yaooqinn/kyuubi/server/KyuubiServerSuite.scala, src/test/scala/yaooqinn/kyuubi/utils/ReflectUtilsSuite.scala
set this to `$KYUUBI_HOME/local` by default
=> default spark.local.dir which points to /tmp is some kind of dangerous

docs/building.md, docs/issue_template.md, src/main/scala/org/apache/spark/SparkEnv.scala
=> fix #82 Start-SparkContext-xxx thread throws java.lang.AbstractMethodError with spark 2.3.0

kyuubi-server/src/main/scala/yaooqinn/kyuubi/server/FrontendService.scala
FrontService  getUserName method is not thread safe  because of the variable ` realUser`
=> 修复可能存在并发opensession的时候，realUser 可能会获取另一个session 的user

kyuubi-server/src/main/scala/yaooqinn/kyuubi/spark/SparkSessionCacheManager.scala, kyuubi-server/src/test/scala/yaooqinn/kyuubi/spark/SparkSessionCacheManagerSuite.scala
=> User Latest Logout information should be cleaned after backend session is stopped by session cache manager

kyuubi-server/src/main/scala/yaooqinn/kyuubi/operation/AbstractOperation.scala, kyuubi-server/src/main/scala/yaooqinn/kyuubi/operation/LogDivertAppender.scala, kyuubi-server/src/main/scala/yaooqinn/kyuubi/operation/LogFile.scala, kyuubi-server/src/main/scala/yaooqinn/kyuubi/operation/OperationLog.scala, kyuubi-server/src/main/scala/yaooqinn/kyuubi/operation/OperationManager.scala, kyuubi-server/src/main/scala/yaooqinn/kyuubi/operation/statement/ExecuteStatementOperation.scala, kyuubi-server/src/test/scala/yaooqinn/kyuubi/operation/OperationManagerSuite.scala
=> [KYUUBI-230] Re-implement OperationLog

README.md
=> [DOCS] Migrate to travis-ci.com

bin/kyuubi-ctl, bin/load-kyuubi-env.sh, conf/log4j.properties.template, docs/deployment/settings.md, kyuubi-common/src/main/scala/org/apache/kyuubi/Logging.scala, kyuubi-ctl/src/main/scala/org/apache/kyuubi/ctl/CommandLineUtils.scala, kyuubi-ctl/src/main/scala/org/apache/kyuubi/ctl/ServiceControlCli.scala, kyuubi-ctl/src/main/scala/org/apache/kyuubi/ctl/ServiceControlCliArguments.scala, kyuubi-ctl/src/test/scala/org/apache/kyuubi/ctl/ServiceControlCliSuite.scala
Improve kyuubi ctl verbose output.
=> [KYUUBI #684]Improve kyuubi ctl verbose output

.asf.yaml
Make `dev/merge_kyuubi_pr.py` available.
=> Remove striction in .asf.yaml

dev/merge_kyuubi_pr.py
change GITHUB_API_BASE = "https://api.github.com/repos/NetEase/kyuubi"
to GITHUB_API_BASE = "https://api.github.com/repos/apache/incubator-kyuubi"
=> [BUILD] Update PR Merge tool

.asf.yaml
=> Set protected_branches explicitly in a nonstrict way

.travis.yml
the Travis ci is not very powerful, we low its workload to a test with default profiles and use it as a backup when GA is out of service sometimes.
=> [BUILD] Minimize the build of travis

.asf.yaml
The branch protection breaks our pr merge tool
=> [INFRA] Disable branches protection

.asf.yaml
=> [INFRA] Format asf yaml

.asf.yaml
Reverts apache/incubator-kyuubi#796
=> Revert "[INFRA] Format asf yaml"

.asf.yaml
=> [MINOR] Remove comments

kyuubi-common/src/main/scala/org/apache/kyuubi/Utils.scala, kyuubi-common/src/main/scala/org/apache/kyuubi/service/FrontendService.scala, kyuubi-common/src/test/scala/org/apache/kyuubi/KyuubiFunSuite.scala, kyuubi-common/src/test/scala/org/apache/kyuubi/UtilsSuite.scala, kyuubi-common/src/test/scala/org/apache/kyuubi/operation/JDBCTestUtils.scala, kyuubi-zookeeper/src/main/scala/org/apache/kyuubi/zookeeper/EmbeddedZookeeper.scala
Find local InetAddress if it's a loopback
=> Find local InetAddress

externals/kyuubi-spark-monitor/src/main/scala/org/apache/kyuubi/engine/spark/monitor/entity/KyuubiStatementInfo.scala
=> [MINOR] Remove useless param comment

.asf.yaml
=> [INFRA] Explicitly remove protected_branches

.asf.yaml
=> Fix notifications indention in .asf.yaml

kyuubi-common/src/test/scala/org/apache/kyuubi/operation/BasicJDBCTests.scala
Workaround to recover Minikube test until #937 is solved.
=> [KYUUBI #956][FOLLOWUP] Temporarily ignore get schemas test

.github/workflows/image.yml
=> [DEV] Push docker image

kyuubi-server/src/main/scala/org/apache/kyuubi/server/KyuubiServer.scala
=> [KYUUBI #1449][BACKPORT][FOLLOWUP] Fix import

kyuubi-common/src/main/scala/org/apache/kyuubi/session/SessionManager.scala
=> [KYUUBI-2422][1.5] Wrap close session with try-finally

docs/deployment/settings.md, kyuubi-common/src/main/scala/org/apache/kyuubi/config/KyuubiConf.scala, kyuubi-server/src/main/scala/org/apache/kyuubi/engine/EngineRef.scala, kyuubi-server/src/main/scala/org/apache/kyuubi/engine/jdbc/JdbcProcessBuilder.scala, kyuubi-server/src/test/scala/org/apache/kyuubi/engine/jdbc/JdbcProcessBuilderSuite.scala
close https://github.com/apache/incubator-kyuubi/issues/3107#issue-1311302964
=> [KYUUBI #3107] [Subtask] DorisSQLEngine - Add process builder

kyuubi-server/src/test/scala/org/apache/kyuubi/server/BackendServiceMetricSuite.scala
=> [KYUUBI #4876] Fix flaky test BackendServiceMetricSuite

kyuubi-server/src/main/scala/org/apache/kyuubi/server/api/v1/BatchesResource.scala
Close #6278 
This pull request fixes #
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
---
**Be nice. Be informative.**
=> [KYUUBI #6278] Update DB state when the query fallback to resource manager and the batch app is terminal
